// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://custom_scrollview',
  'fluttercandies://demogrouppage',
  'fluttercandies://known-sized',
  'fluttercandies://mainpage',
  'fluttercandies://random-sized',
  'fluttercandies://variable-sized',
];

class Routes {
  const Routes._();

  /// 'show how to build waterfall flow in CustomScrollview.'
  ///
  /// [name] : 'fluttercandies://custom_scrollview'
  ///
  /// [routeName] : 'custom_scrollview'
  ///
  /// [description] : 'show how to build waterfall flow in CustomScrollview.'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesCustomScrollview =
      'fluttercandies://custom_scrollview';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'show how to build a known-sized item with waterfall flow list.'
  ///
  /// [name] : 'fluttercandies://known-sized'
  ///
  /// [routeName] : 'known-sized'
  ///
  /// [description] : 'show how to build a known-sized item with waterfall flow list.'
  ///
  /// [exts] : {group: Complex, order: 1}
  static const String fluttercandiesKnownSized = 'fluttercandies://known-sized';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'show how to build random-sized item with waterfall flow list.'
  ///
  /// [name] : 'fluttercandies://random-sized'
  ///
  /// [routeName] : 'random-sized'
  ///
  /// [description] : 'show how to build random-sized item with waterfall flow list.'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesRandomSized =
      'fluttercandies://random-sized';

  /// 'show how to build a variable-sized item with waterfall flow list.'
  ///
  /// [name] : 'fluttercandies://variable-sized'
  ///
  /// [routeName] : 'variable-sized'
  ///
  /// [description] : 'show how to build a variable-sized item with waterfall flow list.'
  ///
  /// [exts] : {group: Complex, order: 1}
  static const String fluttercandiesVariableSized =
      'fluttercandies://variable-sized';
}
