// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://custom_scrollview',
  'fluttercandies://mainpage',
  'fluttercandies://random-sized',
];

class Routes {
  const Routes._();

  /// 'show how to build waterfall flow in CustomScrollview.'
  ///
  /// [name] : 'fluttercandies://custom_scrollview'
  ///
  /// [routeName] : 'SliverMasonryGrid'
  ///
  /// [description] : 'show how to build waterfall flow in CustomScrollview.'
  static const String fluttercandiesCustomScrollview =
      'fluttercandies://custom_scrollview';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'show how to build random-sized item with waterfall flow list.'
  ///
  /// [name] : 'fluttercandies://random-sized'
  ///
  /// [routeName] : 'MasonryGridView'
  ///
  /// [description] : 'show how to build random-sized item with waterfall flow list.'
  static const String fluttercandiesRandomSized =
      'fluttercandies://random-sized';
}
